# Generated by Django 4.1.2 on 2023-06-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio', models.PositiveSmallIntegerField()),
                ('descripcion_producto', models.CharField(max_length=200)),
                ('formato', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=80)),
                ('idioma', models.CharField(max_length=70)),
                ('paginas', models.CharField(max_length=4)),
                ('sinopsis', models.CharField(max_length=400)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categoria')),
                ('tipo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tienda.tipoproducto')),
            ],
        ),
    ]
