# Generated by Django 4.1.2 on 2023-06-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('descripcion_producto', models.CharField(max_length=200)),
                ('formato', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=80)),
                ('idioma', models.CharField(max_length=70)),
                ('paginas', models.CharField(max_length=4)),
                ('categoria', models.CharField(max_length=200)),
                ('sinopsis', models.CharField(max_length=400)),
                ('imagen', models.ImageField(null=True, upload_to='tienda')),
            ],
        ),
    ]
