# Generated by Django 4.1.2 on 2023-06-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='paginas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sinopsis',
        ),
    ]
