# Generated by Django 4.1.2 on 2023-06-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
